channels:
  feishu:
    type: feishu
    name: "飞书推送"
    target: "ou_ed1c1ef79f13a9462dea718e57fd2b34"
    format: markdown
    
  webchat:
    type: webchat
    name: "Webchat 推送"
    target: "default"
    format: markdown
